"""Form-based settings dialog — replaces 'Open Config…' (Notepad on YAML).

Exposes the runtime knobs users actually tweak (mic gain, mic device,
Whisper language, polish model, polish timeout, clipboard-restore,
hotkey) plus a one-click Polish-Modell-Update via Ollama pull.

Designed to be safe with Mike's lessons-learned comments in
%APPDATA%\\Kira\\config.yaml: writes are routed through
kira.config_writer.update_scalars which preserves comments and blank
lines verbatim. Power users can fall back to 'Rohconfig öffnen…' for
multi-line values (initial_prompt, context_modes, whisper.model path).
"""
from __future__ import annotations
import logging
import subprocess
from pathlib import Path

from PIL import Image
from PIL.ImageQt import ImageQt
from PyQt6.QtCore import Qt, QObject, QThread, pyqtSignal
from PyQt6.QtGui import QFont, QIcon, QPixmap
from PyQt6.QtWidgets import (
    QComboBox, QDialog, QDialogButtonBox, QDoubleSpinBox, QFormLayout,
    QFrame, QHBoxLayout, QLabel, QLineEdit, QProgressDialog,
    QPushButton, QSpinBox, QVBoxLayout, QWidget,
)

from kira.ui._dialog_style import (
    apply_light_theme,
    light_critical,
    light_information,
    light_warning,
)

from kira.config import default_config_path, load_config
from kira.config_writer import update_scalars

log = logging.getLogger(__name__)
_ASSETS = Path(__file__).resolve().parent.parent.parent / "assets"


def _load_branded_pixmap(size: int) -> QPixmap | None:
    """Load the largest frame from icon-branded.ico and downscale via
    Pillow's LANCZOS to ``size``. QPixmap's native ICO loader picks an
    arbitrary (often 16x16) frame and upscales it to whatever size we
    request — that's what produced the blurry header logo. Pillow lets
    us pick the 256x256 frame explicitly, then downscale once with a
    proper resampling filter, so the result stays crisp at 48 px.
    """
    src = _ASSETS / "icon-branded.ico"
    if not src.exists():
        return None
    try:
        img = Image.open(src)
        ico = getattr(img, "ico", None)
        if ico is not None:
            sizes = sorted(ico.sizes(), key=lambda s: s[0] * s[1])
            if sizes:
                img.size = sizes[-1]  # type: ignore[misc]
                img.load()
        img = img.convert("RGBA").resize(
            (size, size), Image.Resampling.LANCZOS,
        )
        return QPixmap.fromImage(ImageQt(img))
    except Exception:
        log.exception("failed to load icon-branded.ico for header")
        return None


class _PullWorker(QObject):
    """Background ollama.pull(model) — streams events back to the GUI."""
    progress = pyqtSignal(str, int, int)   # status, completed, total
    finished = pyqtSignal(bool, str)       # success, message

    def __init__(self, model_name: str) -> None:
        super().__init__()
        self._model = model_name

    def run(self) -> None:
        try:
            import ollama
        except Exception as e:
            self.finished.emit(False, f"ollama-Library nicht verfügbar: {e}")
            return
        try:
            for event in ollama.pull(self._model, stream=True):
                status = getattr(event, "status", None) or (
                    event.get("status", "") if isinstance(event, dict) else ""
                )
                completed = (
                    getattr(event, "completed", None)
                    or (event.get("completed", 0) if isinstance(event, dict) else 0)
                    or 0
                )
                total = (
                    getattr(event, "total", None)
                    or (event.get("total", 0) if isinstance(event, dict) else 0)
                    or 0
                )
                self.progress.emit(str(status), int(completed), int(total))
            self.finished.emit(True, f"{self._model} ist auf dem aktuellen Stand.")
        except Exception as e:
            log.exception("ollama.pull failed")
            self.finished.emit(False, f"Modell-Update fehlgeschlagen: {e}")


_MINIMAL_CONFIG = """\
# Kira config — auto-generated by Settings dialog.
# Open this file directly for advanced fields (initial_prompt,
# context_modes, whisper.model path).
audio:
  input_gain: 1.0
  input_device: null
whisper:
  language: auto
styler:
  model: gemma3:12b
  timeout_seconds: 30.0
injector:
  restore_clipboard_after_ms: 500
hotkey:
  combo: f8
"""


class SettingsDialog(QDialog):
    """Runtime settings + Polish-Modell update."""

    def __init__(self) -> None:
        super().__init__()
        self.setWindowTitle("Kira-Einstellungen")
        icon_path = _ASSETS / "icon.ico"
        if icon_path.exists():
            self.setWindowIcon(QIcon(str(icon_path)))
        self.setMinimumWidth(560)
        self.setModal(True)
        apply_light_theme(self)

        self._cfg = load_config()
        self._cfg_path = default_config_path()
        self._pull_thread: QThread | None = None
        self._pull_worker: _PullWorker | None = None

        outer = QVBoxLayout(self)
        outer.setContentsMargins(20, 16, 20, 16)
        outer.setSpacing(12)

        outer.addWidget(self._build_header())
        outer.addWidget(self._build_form())
        outer.addWidget(self._build_hint())
        outer.addLayout(self._build_raw_button_row())
        outer.addWidget(self._build_button_box())

    # ----- builders ------------------------------------------------------

    def _build_header(self) -> QWidget:
        # Kira-branded-Icon links (gelber Rounded-Square + 煌), Title mittig,
        # digitalroots-Logo rechts. Spiegelt das Branding aus den anderen
        # Dialogen wider, aber etwas kompakter — Settings ist ein Werkzeug-
        # Dialog, kein Empfangsschirm, also schmaler Header (~52 px).
        host = QWidget()
        row = QHBoxLayout(host)
        row.setContentsMargins(0, 0, 0, 4)
        row.setSpacing(12)

        kira_label = QLabel()
        kira_pix = _load_branded_pixmap(48)
        if kira_pix is not None:
            kira_label.setPixmap(kira_pix)
        row.addWidget(kira_label)

        row.addStretch()

        title = QLabel("Kira-Einstellungen")
        title_font = QFont()
        title_font.setPointSize(14)
        title_font.setBold(True)
        title.setFont(title_font)
        row.addWidget(title)

        row.addStretch()

        dr_label = QLabel()
        dr_logo = _ASSETS / "digitalroots-logo.png"
        if dr_logo.exists():
            dr_pix = QPixmap(str(dr_logo)).scaledToHeight(
                26, Qt.TransformationMode.SmoothTransformation,
            )
            dr_label.setPixmap(dr_pix)
        row.addWidget(dr_label)

        # dünne Trennlinie unter dem Header
        wrapper = QWidget()
        wrap = QVBoxLayout(wrapper)
        wrap.setContentsMargins(0, 0, 0, 0)
        wrap.setSpacing(8)
        wrap.addWidget(host)
        sep = QFrame()
        sep.setFrameShape(QFrame.Shape.HLine)
        sep.setFrameShadow(QFrame.Shadow.Sunken)
        sep.setStyleSheet("color: #d8d8d8;")
        wrap.addWidget(sep)
        return wrapper

    def _build_form(self) -> QWidget:
        host = QWidget()
        form = QFormLayout(host)
        form.setLabelAlignment(Qt.AlignmentFlag.AlignRight)
        form.setHorizontalSpacing(14)
        form.setVerticalSpacing(8)

        # Audio
        self._gain = QDoubleSpinBox()
        self._gain.setRange(0.1, 200.0)
        self._gain.setSingleStep(0.5)
        self._gain.setDecimals(1)
        self._gain.setValue(self._cfg.audio.input_gain)
        self._gain.setToolTip(
            "Software-Gain auf das rohe Mic-Signal.\n"
            "Sweet Spot: peak 0.3–0.9, rms 0.05–0.15 (siehe kira.log)."
        )
        form.addRow("<b>Mic-Gain</b>", self._gain)

        self._device = QLineEdit()
        self._device.setText(
            "" if self._cfg.audio.input_device is None
            else str(self._cfg.audio.input_device)
        )
        self._device.setPlaceholderText("leer = Windows-Default")
        self._device.setToolTip(
            "Substring des Mikrofon-Namens (case-insensitive).\n"
            "Beispiel: 'ROG Theta', 'Headset', 'Realtek'.\n"
            "Leer = Windows-Default (kann durch Noise-Cancel-Filter routen)."
        )
        form.addRow("<b>Mikrofon</b>", self._device)

        # Whisper
        self._language = QComboBox()
        self._language.addItems(["auto", "de", "en"])
        self._language.setCurrentText(self._cfg.whisper.language)
        form.addRow("<b>Whisper-Sprache</b>", self._language)

        # Styler / Polish
        polish_row = QHBoxLayout()
        self._styler_model = QLineEdit()
        self._styler_model.setText(self._cfg.styler.model)
        self._styler_model.setPlaceholderText("z.B. gemma3:12b, qwen3:8b")
        polish_row.addWidget(self._styler_model)
        update_btn = QPushButton("Aktualisieren")
        update_btn.setToolTip(
            "Lädt das aktuelle Polish-Modell neu via ollama pull —\n"
            "z.B. nachdem die Ollama-Library eine neue Modell-Version\n"
            "veröffentlicht hat."
        )
        update_btn.clicked.connect(self._update_polish_model)
        polish_row.addWidget(update_btn)
        form.addRow("<b>Polish-LLM</b>", polish_row)

        self._styler_timeout = QDoubleSpinBox()
        self._styler_timeout.setRange(1.0, 120.0)
        self._styler_timeout.setSingleStep(1.0)
        self._styler_timeout.setDecimals(1)
        self._styler_timeout.setSuffix(" s")
        self._styler_timeout.setValue(self._cfg.styler.timeout_seconds)
        self._styler_timeout.setToolTip(
            "Timeout für den Polish-API-Call. 30 s ist robust für 12B-\n"
            "Modelle im Cold-Start; 5 s reicht für warm gehaltene 2B-Modelle."
        )
        form.addRow("<b>Polish-Timeout</b>", self._styler_timeout)

        # Injector
        self._restore_ms = QSpinBox()
        self._restore_ms.setRange(100, 5000)
        self._restore_ms.setSingleStep(100)
        self._restore_ms.setSuffix(" ms")
        self._restore_ms.setValue(self._cfg.injector.restore_clipboard_after_ms)
        self._restore_ms.setToolTip(
            "Mindest-Wartezeit bevor das Clipboard wiederhergestellt wird.\n"
            "Lange Diktate skalieren automatisch (~2 ms pro Zeichen ab 80 chars)."
        )
        form.addRow("<b>Clipboard-Restore</b>", self._restore_ms)

        # Hotkey
        self._hotkey = QLineEdit()
        self._hotkey.setText(self._cfg.hotkey.combo)
        self._hotkey.setPlaceholderText("z.B. f8, ctrl+shift+space")
        self._hotkey.setToolTip(
            "PTT-Hotkey-Combo (Format der `keyboard`-lib).\n"
            "Änderung wirkt nach Kira-Neustart."
        )
        form.addRow("<b>Hotkey</b>", self._hotkey)

        return host

    def _build_hint(self) -> QLabel:
        hint = QLabel(
            "<span style='color:#888;'>"
            "Änderungen wirken nach Kira-Neustart. Felder wie "
            "<code>whisper.model</code>, <code>initial_prompt</code> oder "
            "<code>context_modes</code> sind komplexer und werden über die "
            "Rohconfig bearbeitet."
            "</span>"
        )
        hint.setWordWrap(True)
        return hint

    def _build_raw_button_row(self) -> QHBoxLayout:
        row = QHBoxLayout()
        row.addStretch()
        raw_btn = QPushButton("Rohconfig öffnen…")
        raw_btn.setToolTip("Öffnet config.yaml in Notepad für komplexe Felder.")
        raw_btn.clicked.connect(self._open_raw)
        row.addWidget(raw_btn)
        return row

    def _build_button_box(self) -> QDialogButtonBox:
        box = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Save
            | QDialogButtonBox.StandardButton.Cancel
        )
        box.button(QDialogButtonBox.StandardButton.Save).setText("Speichern")
        box.button(QDialogButtonBox.StandardButton.Cancel).setText("Abbrechen")
        box.accepted.connect(self._save)
        box.rejected.connect(self.reject)
        return box

    # ----- handlers ------------------------------------------------------

    def _open_raw(self) -> None:
        self._cfg_path.parent.mkdir(parents=True, exist_ok=True)
        if not self._cfg_path.exists():
            self._cfg_path.write_text(_MINIMAL_CONFIG, encoding="utf-8")
        subprocess.Popen(["notepad.exe", str(self._cfg_path)])

    def _save(self) -> None:
        device_text = self._device.text().strip()
        updates = {
            "audio.input_gain": float(self._gain.value()),
            "audio.input_device": device_text or None,
            "whisper.language": self._language.currentText(),
            "styler.model": self._styler_model.text().strip(),
            "styler.timeout_seconds": float(self._styler_timeout.value()),
            "injector.restore_clipboard_after_ms": int(self._restore_ms.value()),
            "hotkey.combo": self._hotkey.text().strip(),
        }

        self._cfg_path.parent.mkdir(parents=True, exist_ok=True)
        if not self._cfg_path.exists():
            self._cfg_path.write_text(_MINIMAL_CONFIG, encoding="utf-8")

        try:
            current = self._cfg_path.read_text(encoding="utf-8")
            updated = update_scalars(current, updates)
            self._cfg_path.write_text(updated, encoding="utf-8")
        except KeyError as e:
            light_warning(
                self, "Kira",
                f"Config hat unbekanntes Schema ({e}).\n\n"
                "Bitte einmalig 'Rohconfig öffnen…' und sicherstellen, "
                "dass alle Sections (audio / whisper / styler / injector / "
                "hotkey) mit den Feldern existieren.",
            )
            return
        except Exception as e:
            log.exception("settings save failed")
            light_critical(self, "Kira", f"Speichern fehlgeschlagen: {e}")
            return

        light_information(
            self, "Kira",
            "Einstellungen gespeichert.\n\n"
            "Die meisten Änderungen wirken nach Kira-Neustart "
            "(Tray → Quit Kira, dann neu starten).",
        )
        self.accept()

    def _update_polish_model(self) -> None:
        model_name = self._styler_model.text().strip()
        if not model_name:
            light_warning(self, "Kira", "Bitte erst ein Polish-Modell eintragen.")
            return

        progress = QProgressDialog(
            f"Lade {model_name}…", "Abbrechen", 0, 0, self,
        )
        progress.setWindowModality(Qt.WindowModality.WindowModal)
        progress.setWindowTitle("Kira — Modell-Update")
        progress.setMinimumDuration(0)
        # QProgressDialog is a QDialog subclass — apply_light_theme flips
        # palette + QSS so the label/cancel button stay readable in
        # Win11 dark mode while the pull streams.
        apply_light_theme(progress)
        progress.show()

        thread = QThread(self)
        worker = _PullWorker(model_name)
        worker.moveToThread(thread)
        thread.started.connect(worker.run)

        def on_progress(status: str, completed: int, total: int) -> None:
            if total > 0:
                progress.setMaximum(total)
                progress.setValue(completed)
                pct = (completed / total) * 100
                mb_done = completed / (1024 * 1024)
                mb_total = total / (1024 * 1024)
                progress.setLabelText(
                    f"{status}\n{mb_done:.1f} / {mb_total:.1f} MB ({pct:.0f}%)"
                )
            else:
                progress.setLabelText(status or f"Lade {model_name}…")

        def on_finished(success: bool, message: str) -> None:
            progress.close()
            thread.quit()
            thread.wait()
            if success:
                light_information(self, "Kira", message)
            else:
                light_critical(self, "Kira", message)

        worker.progress.connect(on_progress)
        worker.finished.connect(on_finished)
        thread.start()
        # Keep refs alive until the worker finishes.
        self._pull_thread = thread
        self._pull_worker = worker
